spring:
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  elasticsearch:
    uris: http://3.37.165.140:9200
    username: elastic
    password: elastic

  application:
    name: WAY
  datasource:
    url: jdbc:mysql://way.cxwcymyyu51z.ap-northeast-2.rds.amazonaws.com:3306/way
    username: admin
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 150000
      idle-timeout: 100000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 879999247780-4fp5p1tudr20tmn6u46tqb0lukmpcmqb.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: jXtHHVhzKJOyo5w2UZ5p
            client-secret: Ye9c8l77aW
            client-name: Naver
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: 289b00ad2e01aaf2f3cbf209a97a53ed
            client-secret: x2S6QFWPTtOxOpUw0vzkReEDKebHOqwG
            client-name: Kakao
            client-authentication-method: client_secret_post
            redirect-uri: http://3.34.10.59/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  data:
    mongodb:
      uri: mongodb+srv://likelionway:WHlw86ADW5As0qzX@cluster-way.b8k6y.mongodb.net/WAY?retryWrites=true&w=majority&appName=Cluster-WAY

  kafka:
    bootstrap-servers: 3.39.111.170:9092
    consumer:
      group-id: chat-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080
jwt:
  secretKey: 12345678901234567890123456789012
  refreshKey: 12345678901234567890123456789012

image:
  upload:
    dir: /Users/jeonghohyeon/Desktop/WAY


cloud:
  aws:
    credentials:
      access-key: AKIA2UC275TYMQWKWS5I
      secret-key: 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

    s3:
      bucketName: likelionway-image

    region:
      static: ap-northeast-2
      auto: false
